name: Deploy a SiteGround

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependencias
        run: npm install

      - name: Build Next.js
        run: npm run build
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

      - name: Deploy via FTP a SiteGround
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.rickdev.net.pe
          username: ftp-host@rickdev.net.pe
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: /rickdev.net.pe/public_html/
          dangerous-clean-slate: false